declare const str: string;
declare const isFetching: boolean;
declare const isLoading: boolean;
declare const int: number;
declare const float: number;
declare const num: number;
declare const message: string;
declare const numberArray: number[];
declare const numberArray2: Array<number>;
declare const world: string[];
declare const contact: [string, number];
declare let variable: any;
declare function sayMyName(name: string): void;
declare function trowError(message: string): never;
declare function infinite(): never;
declare type Login = string;
declare const login: Login;
declare type ID = string | number;
declare const id1: ID;
declare const id2: ID;
declare type SomeType = string | null | undefined;
